# Default values for helm-chart-ssc-pipeline.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  host:
  namespace: ci
  registry:
    server: quay.io
    user: rh-ee-amiralle
  workspaces:
    pvcWorkspace: shared-workspace

rox:
  central:
    endpoint:

storage:
  pvc:
    create: true
    accessMode: ReadWriteOnce
    resources: 1Gi

image:
  name: quay.io/rh-ee-amiralle/quarkus-fruits-api
  tag: "1.0.0"

nameOverride: ""
fullnameOverride: "ssc-pipeline"

