kind: Secret
apiVersion: v1
metadata:
  name: stackrox-secret
  namespace: ci
data:
  rox_api_token:
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: stackrox-endpoint
  namespace: ci
stringData:
  rox_central_endpoint:
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: quay-secret
data:
  .dockerconfigjson:
type: kubernetes.io/dockerconfigjson